### ISSUE TITLE
ValueError: scheme ws(s) is invalid

### ISSUE THREAD

**Issue by MonkeyTB** [zibuyu2015831/xfyun-spark-api#1]
File "E:\xfyun-spark-api-master\xfyun-spark-api-master\spark_gpt\spark_gpt.py", line 389, in _run
    ws.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE})

ValueError: scheme ws(s) is invalid

**Comment by MonkeyTB** [comment]
> File "E:\xfyun-spark-api-master\xfyun-spark-api-master\spark_gpt\spark_gpt.py", line 389, in _run ws.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE})
> 
> ValueError: scheme ws(s) is invalid

的吧 (s)去掉才行

**Comment by lz99316** [comment]
问题解决了么兄弟，我也遇到了
