### ISSUE TITLE
'WebSocketApp' object has no attribute 'question'

### ISSUE THREAD

**Issue by liqinga** [zibuyu2015831/xfyun-spark-api#4]
'WebSocketApp' object has no attribute 'question'
def gen_params(appid, domain, new_question, history_user, histroy_assistant):
    """
    通过appid和用户的提问来生成请参数
    """
    data = {
        "header": {
            "app_id": appid,
            "uid": "1234"
        },
        "parameter": {
            "chat": {
                "domain": domain,
                "temperature": 0.5,
                "max_tokens": 2048
            }
        },
        "payload": {
            "message": {
                "text": [
                    {"role":"user","content":history_user},
                    {"role": "assistant", "content": histroy_assistant},
                    {"role": "user", "content": new_question}
                ]
            }
        }
    }
    return data

**Comment by zibuyu2015831** [comment]
'WebSocketApp' object has no attribute 'question'这个错误不是由于gen_params方法造成的，请检查代码的其他地方，看看有没有类似于ws.question的代码
